export type PaintCategory = "Base" | "Layer" | "Shade" | "Dry" | "Contrast" | "Technical";

export interface VallejoMatch {
  line: "GC" | "MC" | "Wash"; // Game Color / Model Color / Wash
  code: string;
  name: string;
  approx?: boolean; // 完全一致ではなく近似色
}

export interface GundamMatch {
  code: string;
  name: string;
  approx?: boolean;
}

export interface PaintEntry {
  id: string;
  citadel: string;
  category: PaintCategory;
  hex?: string; // おおよその参考色
  vallejo?: VallejoMatch[];
  gundam?: GundamMatch[];
}

export const PAINT_DATA: PaintEntry[] = [
  // ── Base ────────────────────────────────────────────────────────────────────
  {
    id: "abaddon-black",
    citadel: "Abaddon Black",
    category: "Base",
    hex: "#0d0d0d",
    vallejo: [{ line: "GC", code: "72.051", name: "Black" }],
    gundam: [{ code: "XF-1", name: "ブラック" }],
  },
  {
    id: "corax-white",
    citadel: "Corax White",
    category: "Base",
    hex: "#f0f0f0",
    vallejo: [{ line: "GC", code: "72.001", name: "White" }],
    gundam: [{ code: "XF-2", name: "ホワイト" }],
  },
  {
    id: "mephiston-red",
    citadel: "Mephiston Red",
    category: "Base",
    hex: "#8c1a1a",
    vallejo: [{ line: "GC", code: "72.010", name: "Bloody Red", approx: true }],
    gundam: [{ code: "XF-7", name: "フラットレッド", approx: true }],
  },
  {
    id: "khorne-red",
    citadel: "Khorne Red",
    category: "Base",
    hex: "#6b0e0e",
    vallejo: [{ line: "GC", code: "72.011", name: "Gory Red", approx: true }],
  },
  {
    id: "macragge-blue",
    citadel: "Macragge Blue",
    category: "Base",
    hex: "#1b3f6b",
    vallejo: [{ line: "GC", code: "72.022", name: "Ultramarine Blue", approx: true }],
    gundam: [{ code: "XF-8", name: "フラットブルー", approx: true }],
  },
  {
    id: "kantor-blue",
    citadel: "Kantor Blue",
    category: "Base",
    hex: "#0f2b50",
    vallejo: [{ line: "GC", code: "72.023", name: "Imperial Blue", approx: true }],
  },
  {
    id: "caliban-green",
    citadel: "Caliban Green",
    category: "Base",
    hex: "#0e3b1e",
    vallejo: [{ line: "GC", code: "72.028", name: "Dark Green", approx: true }],
    gundam: [{ code: "XF-5", name: "フラットグリーン", approx: true }],
  },
  {
    id: "averland-sunset",
    citadel: "Averland Sunset",
    category: "Base",
    hex: "#e8920d",
    vallejo: [{ line: "GC", code: "72.007", name: "Gold Yellow", approx: true }],
    gundam: [{ code: "XF-3", name: "フラットイエロー", approx: true }],
  },
  {
    id: "jokaero-orange",
    citadel: "Jokaero Orange",
    category: "Base",
    hex: "#c94510",
    vallejo: [{ line: "GC", code: "72.008", name: "Orange Fire", approx: true }],
  },
  {
    id: "zandri-dust",
    citadel: "Zandri Dust",
    category: "Base",
    hex: "#a58a5a",
    vallejo: [
      { line: "GC", code: "72.061", name: "Plague Brown", approx: true },
      { line: "MC", code: "70.819", name: "Iraqi Sand", approx: true },
    ],
  },
  {
    id: "steel-legion-drab",
    citadel: "Steel Legion Drab",
    category: "Base",
    hex: "#7a6840",
    vallejo: [{ line: "MC", code: "70.873", name: "US Field Drab", approx: true }],
  },
  {
    id: "rhinox-hide",
    citadel: "Rhinox Hide",
    category: "Base",
    hex: "#4a2e1c",
    vallejo: [
      { line: "GC", code: "72.045", name: "Charred Brown", approx: true },
      { line: "MC", code: "70.984", name: "Flat Brown", approx: true },
    ],
  },
  {
    id: "rakarth-flesh",
    citadel: "Rakarth Flesh",
    category: "Base",
    hex: "#b5a185",
    vallejo: [
      { line: "GC", code: "72.034", name: "Bonewhite", approx: true },
      { line: "MC", code: "70.837", name: "Pale Sand", approx: true },
    ],
  },
  {
    id: "wraithbone",
    citadel: "Wraithbone",
    category: "Base",
    hex: "#d4c98a",
    vallejo: [
      { line: "GC", code: "72.034", name: "Bonewhite", approx: true },
      { line: "MC", code: "70.837", name: "Pale Sand", approx: true },
    ],
  },
  {
    id: "grey-seer",
    citadel: "Grey Seer",
    category: "Base",
    hex: "#c2c2c0",
    vallejo: [{ line: "GC", code: "72.102", name: "Stonewall Grey", approx: true }],
  },
  {
    id: "celestra-grey",
    citadel: "Celestra Grey",
    category: "Base",
    hex: "#8a9ba0",
    vallejo: [
      { line: "GC", code: "72.102", name: "Stonewall Grey", approx: true },
      { line: "MC", code: "70.990", name: "Light Grey", approx: true },
    ],
  },
  {
    id: "leadbelcher",
    citadel: "Leadbelcher",
    category: "Base",
    hex: "#787878",
    vallejo: [{ line: "GC", code: "72.054", name: "Gunmetal Metal" }],
    gundam: [{ code: "XF-16", name: "フラットアルミ", approx: true }],
  },
  {
    id: "retributor-armour",
    citadel: "Retributor Armour",
    category: "Base",
    hex: "#c8922a",
    vallejo: [{ line: "GC", code: "72.057", name: "Glorious Gold", approx: true }],
    gundam: [{ code: "XF-6", name: "カッパー", approx: true }],
  },
  {
    id: "balthasar-gold",
    citadel: "Balthasar Gold",
    category: "Base",
    hex: "#a07030",
    vallejo: [
      { line: "GC", code: "72.057", name: "Glorious Gold", approx: true },
      { line: "MC", code: "70.996", name: "Gold", approx: true },
    ],
  },
  {
    id: "xv-88",
    citadel: "XV-88",
    category: "Base",
    hex: "#8a6a30",
    vallejo: [
      { line: "GC", code: "72.061", name: "Plague Brown", approx: true },
      { line: "MC", code: "70.912", name: "Tan Yellow", approx: true },
    ],
  },
  {
    id: "naggaroth-night",
    citadel: "Naggaroth Night",
    category: "Base",
    hex: "#3b1f4a",
    vallejo: [{ line: "GC", code: "72.016", name: "Royal Purple", approx: true }],
  },
  {
    id: "xereus-purple",
    citadel: "Xereus Purple",
    category: "Base",
    hex: "#4a2060",
    vallejo: [{ line: "GC", code: "72.016", name: "Royal Purple", approx: true }],
  },
  {
    id: "screamer-pink",
    citadel: "Screamer Pink",
    category: "Base",
    hex: "#8c2050",
    vallejo: [{ line: "GC", code: "72.014", name: "Warlord Purple", approx: true }],
  },
  {
    id: "mechanicus-standard-grey",
    citadel: "Mechanicus Standard Grey",
    category: "Base",
    hex: "#484848",
    vallejo: [{ line: "MC", code: "70.992", name: "Neutral Grey", approx: true }],
    gundam: [{ code: "XF-54", name: "ダークシーグレイ", approx: true }],
  },
  {
    id: "death-world-forest",
    citadel: "Death World Forest",
    category: "Base",
    hex: "#5a6b38",
    vallejo: [{ line: "MC", code: "70.893", name: "US Dark Green", approx: true }],
  },
  {
    id: "gal-vorbak-red",
    citadel: "Gal Vorbak Red",
    category: "Base",
    hex: "#5a1010",
    vallejo: [{ line: "GC", code: "72.012", name: "Scarlet Red", approx: true }],
  },
  {
    id: "thousand-sons-blue",
    citadel: "Thousand Sons Blue",
    category: "Base",
    hex: "#1a5070",
    vallejo: [{ line: "GC", code: "72.022", name: "Ultramarine Blue", approx: true }],
  },
  {
    id: "waaagh-flesh",
    citadel: "Waaagh! Flesh",
    category: "Base",
    hex: "#2a4820",
    vallejo: [{ line: "GC", code: "72.028", name: "Dark Green", approx: true }],
  },
  // ── Layer ───────────────────────────────────────────────────────────────────
  {
    id: "evil-sunz-scarlet",
    citadel: "Evil Sunz Scarlet",
    category: "Layer",
    hex: "#cc2200",
    vallejo: [{ line: "GC", code: "72.010", name: "Bloody Red" }],
  },
  {
    id: "wild-rider-red",
    citadel: "Wild Rider Red",
    category: "Layer",
    hex: "#e04010",
    vallejo: [{ line: "GC", code: "72.008", name: "Orange Fire", approx: true }],
  },
  {
    id: "troll-slayer-orange",
    citadel: "Troll Slayer Orange",
    category: "Layer",
    hex: "#e86010",
    vallejo: [{ line: "GC", code: "72.008", name: "Orange Fire", approx: true }],
  },
  {
    id: "yriel-yellow",
    citadel: "Yriel Yellow",
    category: "Layer",
    hex: "#f0c400",
    vallejo: [{ line: "GC", code: "72.006", name: "Sun Yellow" }],
  },
  {
    id: "flash-gitz-yellow",
    citadel: "Flash Gitz Yellow",
    category: "Layer",
    hex: "#f8e000",
    vallejo: [{ line: "GC", code: "72.006", name: "Sun Yellow", approx: true }],
  },
  {
    id: "moot-green",
    citadel: "Moot Green",
    category: "Layer",
    hex: "#00cc44",
    vallejo: [{ line: "GC", code: "72.025", name: "Escorpena Green", approx: true }],
  },
  {
    id: "warpstone-glow",
    citadel: "Warpstone Glow",
    category: "Layer",
    hex: "#20a020",
    vallejo: [{ line: "GC", code: "72.025", name: "Escorpena Green", approx: true }],
  },
  {
    id: "skarsnik-green",
    citadel: "Skarsnik Green",
    category: "Layer",
    hex: "#50b050",
    vallejo: [{ line: "GC", code: "72.024", name: "Goblin Green", approx: true }],
  },
  {
    id: "hoeth-blue",
    citadel: "Hoeth Blue",
    category: "Layer",
    hex: "#4a7fc0",
    vallejo: [{ line: "GC", code: "72.021", name: "Magic Blue" }],
  },
  {
    id: "altdorf-guard-blue",
    citadel: "Altdorf Guard Blue",
    category: "Layer",
    hex: "#2a5fa0",
    vallejo: [{ line: "GC", code: "72.022", name: "Ultramarine Blue", approx: true }],
  },
  {
    id: "calgar-blue",
    citadel: "Calgar Blue",
    category: "Layer",
    hex: "#5080c0",
    vallejo: [{ line: "GC", code: "72.021", name: "Magic Blue", approx: true }],
  },
  {
    id: "lothern-blue",
    citadel: "Lothern Blue",
    category: "Layer",
    hex: "#6090d0",
    vallejo: [{ line: "GC", code: "72.023", name: "Imperial Blue", approx: true }],
  },
  {
    id: "teclis-blue",
    citadel: "Teclis Blue",
    category: "Layer",
    hex: "#70a0e0",
    vallejo: [{ line: "GC", code: "72.020", name: "Glacier Blue", approx: true }],
  },
  {
    id: "pink-horror",
    citadel: "Pink Horror",
    category: "Layer",
    hex: "#c06080",
    vallejo: [{ line: "GC", code: "72.013", name: "Squid Pink", approx: true }],
  },
  {
    id: "genestealer-purple",
    citadel: "Genestealer Purple",
    category: "Layer",
    hex: "#7050a0",
    vallejo: [{ line: "GC", code: "72.016", name: "Royal Purple", approx: true }],
  },
  {
    id: "dawnstone",
    citadel: "Dawnstone",
    category: "Layer",
    hex: "#707070",
    vallejo: [
      { line: "GC", code: "72.101", name: "Ghost Grey", approx: true },
      { line: "MC", code: "70.992", name: "Neutral Grey", approx: true },
    ],
  },
  {
    id: "administratum-grey",
    citadel: "Administratum Grey",
    category: "Layer",
    hex: "#909090",
    vallejo: [
      { line: "GC", code: "72.101", name: "Ghost Grey" },
      { line: "MC", code: "70.990", name: "Light Grey", approx: true },
    ],
  },
  {
    id: "ulthuan-grey",
    citadel: "Ulthuan Grey",
    category: "Layer",
    hex: "#d8dcdc",
    vallejo: [{ line: "MC", code: "70.993", name: "White Grey", approx: true }],
  },
  {
    id: "pallid-wych-flesh",
    citadel: "Pallid Wych Flesh",
    category: "Layer",
    hex: "#e8d8c0",
    vallejo: [{ line: "MC", code: "70.837", name: "Pale Sand", approx: true }],
  },
  {
    id: "ushabti-bone",
    citadel: "Ushabti Bone",
    category: "Layer",
    hex: "#c8b070",
    vallejo: [{ line: "GC", code: "72.034", name: "Bonewhite", approx: true }],
  },
  {
    id: "screaming-skull",
    citadel: "Screaming Skull",
    category: "Layer",
    hex: "#d8c890",
    vallejo: [
      { line: "GC", code: "72.034", name: "Bonewhite", approx: true },
      { line: "MC", code: "70.837", name: "Pale Sand", approx: true },
    ],
  },
  {
    id: "cadian-fleshtone",
    citadel: "Cadian Fleshtone",
    category: "Layer",
    hex: "#c08060",
    vallejo: [{ line: "GC", code: "72.036", name: "Elf Skintone", approx: true }],
    gundam: [{ code: "XF-15", name: "フラットフレッシュ", approx: true }],
  },
  {
    id: "kislev-flesh",
    citadel: "Kislev Flesh",
    category: "Layer",
    hex: "#d09878",
    vallejo: [{ line: "MC", code: "70.845", name: "Sunny Skintone", approx: true }],
  },
  {
    id: "tallarn-sand",
    citadel: "Tallarn Sand",
    category: "Layer",
    hex: "#b89060",
    vallejo: [{ line: "GC", code: "72.061", name: "Plague Brown", approx: true }],
  },
  {
    id: "karak-stone",
    citadel: "Karak Stone",
    category: "Layer",
    hex: "#c0a870",
    vallejo: [
      { line: "GC", code: "72.061", name: "Plague Brown", approx: true },
      { line: "MC", code: "70.837", name: "Pale Sand", approx: true },
    ],
  },
  {
    id: "ironbreaker",
    citadel: "Ironbreaker",
    category: "Layer",
    hex: "#909090",
    vallejo: [{ line: "GC", code: "72.052", name: "Chainmail Silver", approx: true }],
  },
  {
    id: "runefang-steel",
    citadel: "Runefang Steel",
    category: "Layer",
    hex: "#b0b0b0",
    vallejo: [{ line: "GC", code: "72.052", name: "Chainmail Silver" }],
  },
  {
    id: "auric-armour-gold",
    citadel: "Auric Armour Gold",
    category: "Layer",
    hex: "#e0b040",
    vallejo: [{ line: "GC", code: "72.057", name: "Glorious Gold", approx: true }],
  },
  // ── Shade ───────────────────────────────────────────────────────────────────
  {
    id: "nuln-oil",
    citadel: "Nuln Oil",
    category: "Shade",
    hex: "#1a1a1a",
    vallejo: [
      { line: "Wash", code: "73.201", name: "Black Wash" },
    ],
    gundam: [{ code: "Mr.ウェザリングカラー WC05", name: "マルチブラック", approx: true }],
  },
  {
    id: "agrax-earthshade",
    citadel: "Agrax Earthshade",
    category: "Shade",
    hex: "#5c3a18",
    vallejo: [{ line: "Wash", code: "73.200", name: "Sepia Wash" }],
    gundam: [{ code: "Mr.ウェザリングカラー WC02", name: "グランドブラウン", approx: true }],
  },
  {
    id: "reikland-fleshshade",
    citadel: "Reikland Fleshshade",
    category: "Shade",
    hex: "#8b4030",
    vallejo: [{ line: "Wash", code: "73.204", name: "Fleshtone Wash" }],
  },
  {
    id: "carroburg-crimson",
    citadel: "Carroburg Crimson",
    category: "Shade",
    hex: "#7a1830",
    vallejo: [{ line: "Wash", code: "73.205", name: "Red Wash" }],
  },
  {
    id: "druchii-violet",
    citadel: "Druchii Violet",
    category: "Shade",
    hex: "#401858",
    vallejo: [{ line: "Wash", code: "73.207", name: "Violet Wash" }],
  },
  {
    id: "coelia-greenshade",
    citadel: "Coelia Greenshade",
    category: "Shade",
    hex: "#183028",
    vallejo: [{ line: "Wash", code: "73.206", name: "Green Wash" }],
  },
  {
    id: "biel-tan-green",
    citadel: "Biel-Tan Green",
    category: "Shade",
    hex: "#204820",
    vallejo: [{ line: "Wash", code: "73.206", name: "Green Wash", approx: true }],
  },
  {
    id: "drakenhof-nightshade",
    citadel: "Drakenhof Nightshade",
    category: "Shade",
    hex: "#101838",
    vallejo: [{ line: "Wash", code: "73.202", name: "Blue Wash" }],
  },
  {
    id: "athonian-camoshade",
    citadel: "Athonian Camoshade",
    category: "Shade",
    hex: "#304020",
    vallejo: [{ line: "Wash", code: "73.203", name: "Umber Wash", approx: true }],
  },
  {
    id: "casandora-yellow",
    citadel: "Casandora Yellow",
    category: "Shade",
    hex: "#c09000",
    vallejo: [{ line: "Wash", code: "73.208", name: "Yellow Wash" }],
  },
  {
    id: "fuegan-orange",
    citadel: "Fuegan Orange",
    category: "Shade",
    hex: "#b04010",
    vallejo: [{ line: "Wash", code: "73.209", name: "Orange Wash", approx: true }],
  },
  {
    id: "seraphim-sepia",
    citadel: "Seraphim Sepia",
    category: "Shade",
    hex: "#7a5820",
    vallejo: [{ line: "Wash", code: "73.200", name: "Sepia Wash", approx: true }],
  },
  // ── Dry ─────────────────────────────────────────────────────────────────────
  {
    id: "praxeti-white",
    citadel: "Praxeti White",
    category: "Dry",
    hex: "#e8e8e0",
    vallejo: [{ line: "MC", code: "70.993", name: "White Grey", approx: true }],
  },
  {
    id: "etherium-blue",
    citadel: "Etherium Blue",
    category: "Dry",
    hex: "#a0c0d0",
    vallejo: [{ line: "GC", code: "72.020", name: "Glacier Blue", approx: true }],
  },
  {
    id: "necron-compound",
    citadel: "Necron Compound",
    category: "Dry",
    hex: "#c0c0b8",
    vallejo: [{ line: "GC", code: "72.052", name: "Chainmail Silver", approx: true }],
  },
  {
    id: "golden-griffon",
    citadel: "Golden Griffon",
    category: "Dry",
    hex: "#d0a840",
    vallejo: [{ line: "GC", code: "72.057", name: "Glorious Gold", approx: true }],
  },
  // ── Contrast ────────────────────────────────────────────────────────────────
  {
    id: "blood-angels-red",
    citadel: "Blood Angels Red",
    category: "Contrast",
    hex: "#a01818",
    vallejo: [{ line: "GC", code: "72.010", name: "Bloody Red", approx: true }],
  },
  {
    id: "ultramarines-blue",
    citadel: "Ultramarines Blue",
    category: "Contrast",
    hex: "#1c3e6e",
    vallejo: [{ line: "GC", code: "72.022", name: "Ultramarine Blue", approx: true }],
  },
  {
    id: "dark-angels-green",
    citadel: "Dark Angels Green",
    category: "Contrast",
    hex: "#14421a",
    vallejo: [{ line: "GC", code: "72.028", name: "Dark Green", approx: true }],
  },
  {
    id: "skeleton-horde",
    citadel: "Skeleton Horde",
    category: "Contrast",
    hex: "#c0a860",
    vallejo: [{ line: "GC", code: "72.034", name: "Bonewhite", approx: true }],
  },
  {
    id: "gryph-charger-grey",
    citadel: "Gryph-charger Grey",
    category: "Contrast",
    hex: "#7080a0",
    vallejo: [{ line: "MC", code: "70.992", name: "Neutral Grey", approx: true }],
  },
  {
    id: "black-templar",
    citadel: "Black Templar",
    category: "Contrast",
    hex: "#181818",
    vallejo: [{ line: "GC", code: "72.051", name: "Black", approx: true }],
  },
  {
    id: "iyanden-yellow",
    citadel: "Iyanden Yellow",
    category: "Contrast",
    hex: "#d4a000",
    vallejo: [{ line: "GC", code: "72.006", name: "Sun Yellow", approx: true }],
  },
  {
    id: "nazdreg-yellow",
    citadel: "Nazdreg Yellow",
    category: "Contrast",
    hex: "#e8b800",
    vallejo: [{ line: "GC", code: "72.006", name: "Sun Yellow", approx: true }],
  },
  {
    id: "snakebite-leather",
    citadel: "Snakebite Leather",
    category: "Contrast",
    hex: "#8c6020",
    vallejo: [{ line: "MC", code: "70.984", name: "Flat Brown", approx: true }],
  },
  {
    id: "wyldwood",
    citadel: "Wyldwood",
    category: "Contrast",
    hex: "#4a3418",
    vallejo: [{ line: "MC", code: "70.984", name: "Flat Brown", approx: true }],
  },
];

export const CATEGORIES: PaintCategory[] = [
  "Base", "Layer", "Shade", "Dry", "Contrast", "Technical",
];
